# Generated by Django 4.0.6 on 2022-07-30 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_id', models.CharField(max_length=128)),
                ('enter_time', models.DateTimeField(null=True)),
                ('quit_time', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('total_active_days', models.IntegerField(default=0)),
                ('max_active_days_in_a_row', models.IntegerField(default=0)),
                ('group_id', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('image_url', models.URLField(max_length=512)),
                ('is_submitted_later', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.member')),
            ],
        ),
    ]
