# Generated by Django 4.0.6 on 2022-08-01 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('member_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='member',
            old_name='max_active_days_in_a_row',
            new_name='count_failure_in_a_week',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='record_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='group_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='total_active_days',
        ),
        migrations.AddField(
            model_name='member',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task.group'),
        ),
    ]
